default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: tweetypi_development

test:
  <<: *default
  database: tweetypi_test
  
production:
  <<: *default