default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: pay_it_forward_development

test:
  <<: *default
  database: pay_it_forward_test
  
production:
  <<: *default